name: Deploy

on:
  workflow_dispatch:
jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
          echo $branchName
          [[ $branchName = 'staging' ]] && type="staging" || type="release"
          matrix=$(jq --arg branchName "$branchName" 'map(. | select(.type==$branchName) )' .github/workflows/matrix_includes.json)
          echo $matrix
          echo ::set-output name=matrix::{\"include\":$(echo $matrix)}\"
  deploy:
    needs: matrix_prep
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix.config)}}
    steps:
      - run: "echo hello"
